# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-19 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDP', '0023_auto_20161126_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='image_content',
            field=models.FileField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
