# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-04-09 19:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SDP', '0024_auto_20190319_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
